
apiVersion: v1
kind: Pod
metadata: 
  name: webapp
  labels:
    app: webapp
    release: "0"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0
    #command:
    #args:

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-release-0-5
  labels:
    app: webapp
    release: "0-5"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
---
apiVersion: v1
kind: Pod
metadata:
  name: mq
  labels:
    app: mq
    release: "1"
spec:
  containers:
  - name: mq
    image: richardchesterwood/k8s-fleetman-queue:release1
