---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec: 
  # This defines which pods are going to be represented by this service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg. browser)
  ports:
    - name: http
      port: 80
      #nodePort: 30080
  selector: 
    app: webapp-release-0-5
    release: "0-5"
 # type: NodePort
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mq-service
spec:
  ports:
    - name: http
      port: 8161
      nodePort: 30010
  selector:
    app: mq
    release: "1"
  type: NodePort
